---
- name: Copy Dot Files
  shell: cp -pR /vagrant/dot/.[a-z]* /home/vagrant

- name: Build Correct OS Version
  include: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'
