---
- name: Build Ubuntu Version
  include: ubuntu1404.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- name: Build CentOS Version
  include: centos65.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '6.5'
